runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: main.app
  secure: always
